# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_define', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False, verbose_name='主键')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('desc', models.TextField(verbose_name='描述')),
                ('insertDate', models.DateField(auto_now=True, verbose_name='插入时间')),
                ('updateDate', models.DateField(auto_now_add=True, verbose_name='修改时间')),
            ],
        ),
    ]
