# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 08:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model_define', '0002_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(default=2, max_length=254, verbose_name='email'),
            preserve_default=False,
        ),
    ]
