# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-05 07:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='标题')),
                ('tagline', models.TextField(verbose_name='摘要')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255, verbose_name='大标题')),
                ('body_text', models.TextField(verbose_name='文章正文')),
                ('pub_date', models.DateField(verbose_name='发布日期')),
                ('mod_date', models.DateField(auto_now=True, verbose_name='修改日期')),
                ('n_comments', models.IntegerField(verbose_name='评论数')),
                ('n_pingbacks', models.IntegerField(verbose_name='点击数')),
                ('rating', models.IntegerField(verbose_name='论文定级')),
                ('authors', models.ManyToManyField(to='model_query.Author', verbose_name='作者')),
                ('blog', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entry_set', to='model_query.Blog')),
            ],
        ),
    ]
